provider:
  name: digitalocean
env:
  - name: DO_TOKEN
    valueFrom:
      secretKeyRef:
        name: do-dns-secret
        key: password
domainFilters:
  - ${domain}
txtOwnerId: ${cluster_name}
sources:
  - service
  - gateway-httproute
policy: sync