apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.name }}
spec:
  acme:
    server: {{ .Values.server }}
    email: {{ required "A valid .Values.email is required" .Values.email }}
    privateKeySecretRef:
      name: {{ .Values.privateKeySecretName }}
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: {{ .Values.secretName }}
              key: {{ .Values.secretKey }}