apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: proxy-config
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          service.beta.kubernetes.io/do-loadbalancer-name: "gitlab-lb"
          service.beta.kubernetes.io/do-loadbalancer-protocol: "tcp"
          service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"