apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: cert-manager
    namespace: flux-system
  targetNamespace: cert-manager
  install:
    createNamespace: true
  values:
    crds:
      enabled: true
      keep: true

    replicaCount: 1

    prometheus:
      enabled: true

    webhook:
      timeoutSeconds: 25
