apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1m
  timeout: 15m
  dependsOn:
    - name: cert-manager
    - name: dns01-certificate
    - name: reflector
    - name: cluster-issuer
    - name: envoy-gateway
    - name: gateway-config
  chart:
    spec:
      chart: gitlab
      version: 9.11.2
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  targetNamespace: gitlab
  install:
    createNamespace: true
  values:
    global:
      edition: ce

      initialRootPassword:
        secret: gitlab-initial-root-password
        key: password

      hosts:
        domain: ${domain}
        https: true
        gitlab:
          name: ${gitlab_host}.${domain}
        registry:
          name: ${registry_host}.${domain}
        pages:
          name: ${pages_host}.${domain}

      gatewayApi:
        enabled: true
        installEnvoy: false
        configureCertmanager: false
        gatewayRef:
          name: gateway
          namespace: envoy-gateway-system

      ingress:
        enabled: false
        configureCertmanager: false

      psql:
        host: ${postgres_host}
        port: ${postgres_port}
        database: ${postgres_database}
        username: ${postgres_username}
        password:
          secret: gitlab-postgres-secret
          key: password

      redis:
        scheme: rediss
        host: ${redis_host}
        port: ${redis_port}
        auth:
          enabled: true
          secret: gitlab-redis-secret
          key: password

      pages:
        enabled: true

      appConfig:
        object_store:
          enabled: true
          proxy_download: true
          connection:
            secret: gitlab-s3-main-secret
            key: connection

        artifacts:
          bucket: ${buckets_artifacts}
          connection: {}
        uploads:
          bucket: ${buckets_uploads}
          connection: {}
        packages:
          bucket: ${buckets_packages}
          connection: {}
        lfs:
          bucket: ${buckets_lfs}
          connection: {}
        registry:
          bucket: ${buckets_registry}
          connection: {}
        pages:
          bucket: ${buckets_pages}
          connection: {}
        externalDiffs:
          enabled: false
          bucket: ${buckets_external_diffs}
        dependencyProxy:
          enabled: false
          bucket: ${buckets_dependency_proxy}
        ciSecureFiles:
          bucket: ${buckets_ci_secure_files}
          connection: {}

      minio:
        enabled: false

      email:
        display_name: GitLab
        from: gitlab@${domain}
        reply_to: noreply@${domain}

      smtp:
        enabled: true
        domain: smtp.sendgrid.net
        address: smtp.sendgrid.net
        port: 2525
        user_name: apikey
        password:
          secret: gitlab-sendgrid-secret
          key: password
        tls: false
        starttls_auto: true
        openssl_verify_mode: peer

      time_zone: UTC

      extraEnv:
        PGSSLMODE: require


    postgresql:
      install: false
    redis:
      install: false
    gitlab:
      webservice:
        gatewayRoute:
          sectionName: https
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        workhorse:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
      gitlab-shell:
        gatewayRoute:
          sectionName: tcp-ssh
        sshDaemon: gitlab-sshd
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
      gitlab-pages:
        gatewayRoute:
          sectionName: https
      sidekiq:
        metrics:
          enabled: true
          podMonitor:
            enabled: true
      gitlab-exporter:
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
    gitlab-runner:
      install: false
    registry:
      gatewayRoute:
        sectionName: https
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    prometheus:
      install: false
    nginx-ingress:
      enabled: false
    installCertmanager: false