grafana:
  ingress:
    enabled: false
  route:
    main:
      enabled: true
      hostnames:
        - ${grafana_host}.${domain}
      parentRefs:
        - name: envoy-gateway
          namespace: envoy-gateway-system

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    ruleSelector: {}