apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: 1.20.0

      helm:
        valueFiles:
          - $values/helm/external-dns/values.yaml
        valuesObject:
          domain: {{ .Values.domain }}
          cluster_name: {{ .Values.clusterName }}

    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
