global:
  edition: ce

  initialRootPassword:
    secret: gitlab-initial-root-password
    key: password

  hosts:
    domain: ${domain}
    https: true
    gitlab:
      name: ${gitlab_host}.${domain}
    registry:
      name: ${registry_host}.${domain}

  ingress:
    configureCertmanager: false
    class: nginx
    tls:
      enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt

  psql:
    host: ${postgres_host}
    port: ${postgres_port}
    database: ${postgres_database}
    username: ${postgres_username}
    password:
      secret: gitlab-postgres-secret
      key: password

  redis:
    scheme: rediss
    host: ${redis_host}
    port: ${redis_port}
    auth:
      enabled: true
      secret: gitlab-redis-secret
      key: password

  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: gitlab-s3-main-secret
        key: connection

    artifacts:
      bucket: ${buckets["artifacts"]}
      connection: {}
    uploads:
      bucket: ${buckets["uploads"]}
      connection: {}
    packages:
      bucket: ${buckets["packages"]}
      connection: {}
    lfs:
      bucket: ${buckets["lfs"]}
      connection: {}
    registry:
      bucket: ${buckets["registry"]}
      connection: {}

  minio:
    enabled: false

  time_zone: UTC

  extraEnv:
    PGSSLMODE: require


postgresql:
  install: false
redis:
  install: false
gitlab-runner:
  install: false
prometheus:
  install: false
nginx-ingress:
  enabled: false
installCertmanager: false