global:
  edition: ce

  initialRootPassword:
    secret: gitlab-initial-root-password
    key: password

  hosts:
    domain: ${domain}
    https: true
    gitlab:
      name: ${gitlab_host}.${domain}
    registry:
      name: ${registry_host}.${domain}
    pages:
      name: ${pages_host}.${domain}

  gatewayApi:
    enabled: true
    installEnvoy: false
    configureCertmanager: false
    gatewayClass: envoy
    gateway:
      name: gateway
      namespace: envoy-gateway-system

  ingress:
    enabled: false
    configureCertmanager: false

  psql:
    host: ${postgres_host}
    port: ${postgres_port}
    database: ${postgres_database}
    username: ${postgres_username}
    password:
      secret: gitlab-postgres-secret
      key: password

  redis:
    scheme: rediss
    host: ${redis_host}
    port: ${redis_port}
    auth:
      enabled: true
      secret: gitlab-redis-secret
      key: password

  pages:
    enabled: true

  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: gitlab-s3-main-secret
        key: connection

    artifacts:
      bucket: ${buckets["artifacts"]}
      connection: {}
    uploads:
      bucket: ${buckets["uploads"]}
      connection: {}
    packages:
      bucket: ${buckets["packages"]}
      connection: {}
    lfs:
      bucket: ${buckets["lfs"]}
      connection: {}
    registry:
      bucket: ${buckets["registry"]}
      connection: {}
    pages:
      bucket: ${buckets["pages"]}
      connection: {}

  minio:
    enabled: false

  email:
    display_name: GitLab
    from: gitlab@${domain}
    reply_to: noreply@${domain}

  smtp:
    enabled: true
    domain: smtp.sendgrid.net
    address: smtp.sendgrid.net
    port: 2525
    user_name: apikey
    password:
      secret: gitlab-sendgrid-secret
      key: password
    tls: false
    starttls_auto: true
    openssl_verify_mode: peer

  time_zone: UTC

  extraEnv:
    PGSSLMODE: require


postgresql:
  install: false
redis:
  install: false
gitlab:
  webservice:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    workhorse:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
  sidekiq:
    metrics:
      enabled: true
      podMonitor:
        enabled: true
  gitlab-exporter:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  gitlab-shell:
    sshDaemon: gitlab-sshd
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
gitlab-runner:
  install: false
registry:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
prometheus:
  install: false
nginx-ingress:
  enabled: false
installCertmanager: false