apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.secretName }}
  issuerRef:
    name: {{ .Values.issuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.domain }}
  dnsNames:
    {{- range .Values.dnsNameTemplates }}
      - {{ tpl . $ | quote }}
    {{- end }}
  secretTemplate:
    annotations:
    {{- if .Values.reflectNamespaces }}
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{ .Values.reflectNamespaces }}"
    {{- end}}
